### ISSUE TITLE
1.7.9 RuntimeException: Unfixable conflicts

### ISSUE THREAD

**Issue by HowardZHY** [Legacy-Fabric/Legacy-Intermediaries#37]
"C:\Program Files\Java\jdk1.8.0_311\jre\bin\java.exe"  -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dmixin.debug.export=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m "-Djava.library.path=D:\1.7.10\.minecraft\versions\fabric-loader-0.14.9-1.7.9\fabric-loader-0.14.9-1.7.9-natives" -cp "D:\1.7.10\.minecraft\libraries\com\mojang\netty\1.8.8\netty-1.8.8.jar;D:\1.7.10\.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;D:\1.7.10\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;D:\1.7.10\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;D:\1.7.10\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;D:\1.7.10\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;D:\1.7.10\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;D:\1.7.10\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;D:\1.7.10\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;D:\1.7.10\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;D:\1.7.10\.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;D:\1.7.10\.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar;D:\1.7.10\.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;D:\1.7.10\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\1.7.10\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;D:\1.7.10\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;D:\1.7.10\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;D:\1.7.10\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;D:\1.7.10\.minecraft\libraries\com\mojang\authlib\1.5.13\authlib-1.5.13.jar;D:\1.7.10\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;D:\1.7.10\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;D:\1.7.10\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;D:\1.7.10\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;D:\1.7.10\.minecraft\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\fabric-loader\0.14.9\fabric-loader-0.14.9.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\intermediary\1.7.9\intermediary-1.7.9.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.3.0+build.17\tiny-mappings-parser-0.3.0+build.17.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\sponge-mixin\0.11.4+mixin.0.8.5\sponge-mixin-0.11.4+mixin.0.8.5.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\tiny-remapper\0.8.2\tiny-remapper-0.8.2.jar;D:\1.7.10\.minecraft\libraries\net\fabricmc\access-widener\2.1.0\access-widener-2.1.0.jar;D:\1.7.10\.minecraft\libraries\org\ow2\asm\asm\9.3\asm-9.3.jar;D:\1.7.10\.minecraft\libraries\org\ow2\asm\asm-analysis\9.3\asm-analysis-9.3.jar;D:\1.7.10\.minecraft\libraries\org\ow2\asm\asm-commons\9.3\asm-commons-9.3.jar;D:\1.7.10\.minecraft\libraries\org\ow2\asm\asm-tree\9.3\asm-tree-9.3.jar;D:\1.7.10\.minecraft\libraries\org\ow2\asm\asm-util\9.3\asm-util-9.3.jar;D:\1.7.10\.minecraft\versions\1.7.9\1.7.9.jar" -jar "C:\Users\howar\AppData\Roaming\PCL\JavaWrapper.jar" net.fabricmc.loader.launch.knot.KnotClient --username HowardZHY --version fabric-loader-0.14.9-1.7.9 --gameDir "D:\1.7.10\.minecraft\versions\fabric-loader-0.14.9-1.7.9" --assetsDir "D:\1.7.10\.minecraft\assets" --assetIndex 1.7.4 --uuid * --accessToken * --userProperties {} --userType Mojang --height 480 --width 854
Mapping source name conflicts detected:
  bdt METHOD a ((ZI)V) -> [bcr/method_21923, bdt/confirmResult]
  bds METHOD a ((ZI)V) -> [bcr/method_21923, bds/confirmResult]
  bhc METHOD a ((ZI)V) -> [bcr/method_21923, bhc/confirmResult]
  bgd METHOD a ((ZI)V) -> [bcr/method_21923, bgd/confirmResult]
  bcp METHOD a ((ZI)V) -> [bcr/method_21923, bcp/confirmResult]
  bik METHOD a ((ZI)V) -> [bcr/method_21923, bik/confirmResult]
  bav METHOD a ((ZI)V) -> [bcr/method_21923, bav/confirmResult]
  bcr METHOD a ((ZI)V) -> [bcr/method_21923, bcr/confirmResult]
  bcy METHOD a ((ZI)V) -> [bcr/method_21923, bcy/confirmResult]
  bea METHOD a ((ZI)V) -> [bcr/method_21923, bea/confirmResult]
  bhh METHOD a ((ZI)V) -> [bcr/method_21923, bhh/confirmResult]
  blo METHOD a ((ZI)V) -> [bcr/method_21923, blo/confirmResult]
  bie METHOD a ((ZI)V) -> [bcr/method_21923, bie/confirmResult]
  bgk METHOD a ((ZI)V) -> [bcr/method_21923, bgk/confirmResult]
[16:42:01] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.7.9 with Fabric Loader 0.14.9
[16:42:01] [WARN] [FabricLoader/GameRemap]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[16:42:01] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
[16:42:02] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
        at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.RuntimeException: Unfixable conflicts
        at net.fabricmc.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:867)
        at net.fabricmc.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:767)
        at net.fabricmc.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1046)
        at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:898)
        at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:304)
        at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:313)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        ... 6 more

**Comment by HowardZHY** [comment]
weird 'cause ONLY 1.7.9 had this
